apiVersion: v1
kind: Service
metadata:
  name: pip
spec:
  selector:
    app: pelias-pip
  ports:
    - protocol: TCP
      port: 3102
      targetPort: 3102
---
apiVersion: v1
kind: Service
metadata:
  name: pelias-api
spec:
  selector:
    app: pelias-api
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100