apiVersion: batch/v1
kind: Job
metadata:
  name: openstreetmap-importer
  # namespace: geocoder
spec:
  backoffLimit: 0 
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      initContainers:
        - name: openstreetmap-download
          image: pelias/openstreetmap:v6.0.0
          command: ["./bin/download"]
          volumeMounts:
          - name: data-volume
            mountPath: /data
          - name: config-volume
            mountPath: /code/pelias.json
            subPath: pelias.json
      containers:
        - name: openstreetmap-import
          image: pelias/openstreetmap:v6.0.0
          command: ["./bin/start"]
          resources:
            limits:
              cpu: 3
              memory: 16Gi
              ephemeral-storage: 4Gi
          volumeMounts:
            - name: data-volume
              mountPath: /data
            - name: config-volume
              mountPath: /code/pelias.json
              subPath: pelias.json
      restartPolicy: Never
      securityContext:
        fsGroup: 1000
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-volume
        - name: config-volume
          configMap:
            name: pelias-configmap
