apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pelias-placeholder
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./k8s/geocoder/apis/pelias-placeholder
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pelias-pip
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./k8s/geocoder/apis/pelias-pip
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: libpostal
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./k8s/geocoder/apis/libpostal
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: interpolation
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./k8s/geocoder/apis/interpolation
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pelias-api
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./k8s/geocoder/apis/pelias-api
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system
    - name: pelias-pip
    - name: pelias-placeholder
    - name: interpolation
    - name: libpostal