apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: data-importer-volumes
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/geocoder/data-importers/
  interval: 60m
  prune: true
  wait: true
  dependsOn:
    - name: flux-system
