---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: es-cluster
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./k8s/geocoder/elasticsearch
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: es-crds
    - name: es-resources