apiVersion: batch/v1
kind: Job
metadata:
  name: whosonfirst-importer
  namespace: geocoder
spec:
  backoffLimit: 0 
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      initContainers:
        - name: whosonfirst-download
          image: pelias/whosonfirst:v6.0.0
          command: ["./bin/download"]
          env:
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quickstart-es-elastic-user
                  key: elastic
          volumeMounts:
            - name: data-volume
              mountPath: /data
            - name: config-volume
              mountPath: /code/pelias.json
              subPath: pelias.json
      containers:
        - name: whosonfirst-import
          image: pelias/whosonfirst:v6.0.0
          command: ["sleep", "infinity"]
          env:
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quickstart-es-elastic-user
                  key: elastic
          volumeMounts:
            - name: data-volume
              mountPath: /data
            - name: config-volume
              mountPath: /code/pelias.json
              subPath: pelias.json
      restartPolicy: Never
      securityContext:
        fsGroup: 1000
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-volume
        - name: config-volume
          configMap:
            name: pelias-configmap
