apiVersion: apps/v1
kind: Deployment
metadata:
  name: pelias-pip
  namespace: geocoder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pelias-pip
  template:
    metadata:
      labels:
        app: pelias-pip
    spec:
      containers:
        - name: pelias-pip
          image: pelias/pip-service:v2.5.0
          ports:
            - containerPort: 3102          
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: data-volume
              mountPath: /data
          env:
            - name: PELIAS_CONFIG
              value: "/etc/config/pelias.json"
          readinessProbe:
            httpGet:
              path: /-122.683342/48.022614
              port: 3102
            initialDelaySeconds: 160
            timeoutSeconds: 1
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /-122.683342/48.022614
              port: 3102
            initialDelaySeconds: 160
            timeoutSeconds: 1
            periodSeconds: 20               
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
        runAsNonRoot: true              
      volumes:
        - name: config-volume
          configMap:
            name: pelias-configmap
            items:
              - key: pelias.json
                path: pelias.json
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-volume-2
