apiVersion: batch/v1
kind: Job
metadata:
  name: create-index-job
  # namespace: geocoder
spec:
  backoffLimit: 0 
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: schema
        image: pelias/schema:v7.0.0
        command: ["./bin/create_index"]
        volumeMounts:
        - name: data-volume
          mountPath: /data
        - name: config-volume
          mountPath: /code/pelias.json
          subPath: pelias.json
      restartPolicy: Never
      securityContext:
        fsGroup: 1000
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-volume
      - name: config-volume
        configMap:
          name: pelias-configmap