apiVersion: ENC[AES256_GCM,data:Ae4=,iv:Sk9qnL+bkQIcTf3AlmmQcFLkvar227PuIn84hb7/0lM=,tag:OdrsoJo7Y9vaDhtoTxMN6A==,type:str]
data:
    token: ENC[AES256_GCM,data:9/CHhgEq4NQ4gsojRiMBEZm1naskFbaV3ybOORojrfWC0CYsjUzzznoio3t2VHLHvvyJYew8NwZ+Brys8QBaJkNyk3N1GI7o87otOA==,iv:7s2RftZIyox7/MmHyhsYmFKcIZMno1hRg4ezY8V0Qzw=,tag:z8JnE3cErBI49+1bpDSxNw==,type:str]
kind: ENC[AES256_GCM,data:5tsO8Dvh,iv:ycPBs//CsSqmTifwm6rwcPqfxajh1xT8nPJt6OH9XBE=,tag:I7fZxF/LhJIBCpDYaoeu9g==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:iVRKLWO+ZRjWIV6cT4Y+,iv:HBCNh5WnD2bMHrF5XsPT7l8zBpRVKJJmzidZPNbVLsM=,tag:M+RAsjjUYpOSH19E/FDEbw==,type:str]
    namespace: ENC[AES256_GCM,data:f3wUaqVeVHpG5ok=,iv:Egs052mlxznVtjdKg6v5FxM+4P4HVdM6Cd5xGlV+XOA=,tag:ie4M2ahhkNTL2v8g8QWTWA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/phx-01hnn9wb0eg/locations/northamerica-northeast1/keyRings/sops/cryptoKeys/sops-flux-key
          created_at: "2024-03-18T19:17:40Z"
          enc: CiQAS8le3OtLgyPB7Jk15u9k5TJwixSHT91i98+phBvs1ceMd/sSSQBcNhTJuucKHvg9hy1Gz8jz67Ua3ACDpTeNJfzwhnu8PyJqQqjwf6khao52Z4Q9fAD65C7fPSHMmAF3co0u5/Z6/U6vnyWMj4s=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-03-18T19:17:41Z"
    mac: ENC[AES256_GCM,data:A/jRE/FSG41GasBMqilTx4+aZwlcUq4Y/HB9aoZqvYNkKnwk7Mkby7rgC6cJD7arqAxHAd9Hff7DVJmHPf7cV36LQaAN4SFcvc0rZynG9xXqxKXqIyG5lRvKj7KVnJlhk8H1azbsiWD+Bq1o8YZNUFGDd4uYfVb4pf4xyDMK8Hw=,iv:4lXZQHQZKxVgi/R9i7fPYT8lwS576e18Kcwi6zND2cY=,tag:4wtyOjBatZEp0k8dirlvWA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
