apiVersion: apps/v1
kind: Deployment
metadata:
  name: pelias-placeholder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pelias-placeholder
  template:
    metadata:
      labels:
        app: pelias-placeholder
    spec:
      containers:
        - name: pelias-placeholder
          image: pelias/placeholder:latest
          ports:
            - containerPort: 3000          
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: data-volume
              mountPath: /data
          env:
            - name: PELIAS_CONFIG
              value: "/etc/config/pelias.json"
      volumes:
        - name: config-volume
          configMap:
            name: pelias-configmap
            items:
              - key: pelias.json
                path: pelias.json
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-volume
