apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: geocoder-app
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./k8s/geocoder/apis/pelias-api
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system