apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pelias-placeholder
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./k8s/geocoder/apis/pelias-placeholder
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pelias-pip
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./k8s/geocoder/apis/pelias-pip
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: libpostal
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./k8s/geocoder/apis/libpostal
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: interpolation
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./k8s/geocoder/apis/interpolation
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pelias-api
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./k8s/geocoder/apis/pelias-api
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: pelias-pip
    - name: pelias-placeholder
    - name: interpolation
    - name: libpostal
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: es-cluster
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./k8s/geocoder/elasticsearch
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: es-crds
    - name: es-resources
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: data-importer-volumes
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/geocoder/data-importers/
  interval: 2m0s
  prune: true
  wait: true
  dependsOn:
    - name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rate-limit
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/geocoder/rate-limit/
  interval: 2m0s
  prune: true
  wait: true
  dependsOn:
    - name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pelias-dashboard
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./k8s/geocoder/dashboard/
  interval: 2m0s
  prune: true
  wait: true
  dependsOn:
    - name: es-cluster
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: geocoder
  namespace: flux-system
spec:
  image: northamerica-northeast1-docker.pkg.dev/phx-01hnn9wb0eg/pelias-geocoder/ui
  interval: 1m0s
  provider: gcp
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: geocoder
  namespace: flux-system
spec:
  filterTags:
    extract: $ts
    pattern: ^main-[a-fA-F0-9]+-(?P<ts>.*)
  imageRepositoryRef:
    name: geocoder
  policy:
    numerical:
      order: asc
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: geocoder-image-updater
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 5m
  update:
    strategy: Setters
    path: .
  git:
    checkout:
      ref:
        branch: "main"
    commit:
      author:
        name: fluxbot
        email: fluxcd@users.noreply.github.com
      messageTemplate: "[ci skip] {{range .Updated.Images}}{{println .}}{{end}}"
    push:
      branch: "main"