apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - openaddress-import/openaddress-import-job.yaml
  - openstreetmap-import/openstreetmap-import-job.yaml
  - whosonfirst-import/whosonfirst-import-job.yaml
  - placeholder-prepare/prepare-placeholder-job.yaml
  - polylines-import/polylines-import-job.yaml
  - pre-import/schema-job.yaml
  - volumes/pelias-configmap.yaml
  - volumes/pelias-pvc.yaml