apiVersion: batch/v1
kind: Job
metadata:
  name: openaddresses-importer
spec:
  backoffLimit: 0 
  template:
    spec:
      initContainers:
        - name: openaddresses-download
          image: pelias/openaddresses:master
          command: ["./bin/download"]
          volumeMounts:
          - name: data-volume
            mountPath: /data
          - name: config-volume
            mountPath: /code/pelias.json
            subPath: pelias.json
          - name: config-volume
            mountPath: /data/blacklist/osm.txt
            subPath: osm.txt
      containers:
        - name: openaddresses-import
          image: pelias/openaddresses:master
          command: ["./bin/start"]
          resources:
            limits:
              cpu: 2
              memory: 16Gi
          volumeMounts:
            - name: data-volume
              mountPath: /data
            - name: config-volume
              mountPath: /code/pelias.json
              subPath: pelias.json
            - name: config-volume
              mountPath: /data/blacklist/osm.txt
              subPath: osm.txt
      restartPolicy: Never
      securityContext:
        fsGroup: 1000
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-volume
        - name: config-volume
          configMap:
            name: pelias-configmap
