apiVersion: batch/v1
kind: Job
metadata:
  name: prepare-placeholder
spec:
  backoffLimit: 0   
  template:
    spec:
      initContainers:
        - name: prepare-placeholder-extract
          image: pelias/placeholder:latest
          command: ["./cmd/extract.sh"]
          volumeMounts:
            - name: data-volume
              mountPath: /data
            - name: config-volume
              mountPath: /code/pelias.json
              subPath: pelias.json
      containers:
        - name: prepare-placeholder-build
          image: pelias/placeholder:latest
          command: ["./cmd/build.sh"]  
          volumeMounts:
            - name: data-volume
              mountPath: /data
            - name: config-volume
              mountPath: /code/pelias.json
              subPath: pelias.json             
      restartPolicy: Never
      securityContext:
        fsGroup: 1000
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-volume
        - name: config-volume
          configMap:
            name: pelias-configmap              