apiVersion: batch/v1
kind: Job
metadata:
  name: whosonfirst-importer
spec:
  backoffLimit: 0 
  template:
    spec:
      initContainers:
        - name: whosonfirst-download
          image: pelias/whosonfirst:master
          command: ["./bin/download"]
          volumeMounts:
            - name: data-volume
              mountPath: /data
            - name: config-volume
              mountPath: /code/pelias.json
              subPath: pelias.json
      containers:
        - name: whosonfirst-import
          image: pelias/whosonfirst:master
          command: ["./bin/start"]
          volumeMounts:
            - name: data-volume
              mountPath: /data
            - name: config-volume
              mountPath: /code/pelias.json
              subPath: pelias.json
      restartPolicy: Never
      securityContext:
        fsGroup: 1000
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-volume
        - name: config-volume
          configMap:
            name: pelias-configmap
