apiVersion: apps/v1
kind: Deployment
metadata:
  name: libpostal
  namespace: geocoder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: libpostal
  template:
    metadata:
      labels:
        app: libpostal
    spec:
      containers:
        - name: libpostal
          image: pelias/libpostal-service:master-2023-12-01-b360390646d4d576ded7ab7fd97d2c081ae1003a
          ports:
            - containerPort: 4400          
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
          env:
            - name: PELIAS_CONFIG
              value: "/etc/config/pelias.json"
          readinessProbe:
            httpGet:
              path: /ping
              port: 4400
            initialDelaySeconds: 5
            timeoutSeconds: 1
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ping
              port: 4400
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 20              
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
        runAsNonRoot: true               
      volumes:
        - name: config-volume
          configMap:
            name: pelias-configmap 
            items:
              - key: pelias.json
                path: pelias.json

