apiVersion: v1
kind: Service
metadata:
    name: libpostal
    namespace: geocoder
spec:
    selector:
        app: libpostal
    ports:
        - protocol: TCP
          port: 4400
          targetPort: 4400
