apiVersion: apps/v1
kind: Deployment
metadata:
  name: pelias-api
  namespace: geocoder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pelias-api
  template:
    metadata:
      labels:
        app: pelias-api
    spec:
      containers:
        - name: pelias-api-cnt
          image: pelias/api:master-2024-03-20-e6f532b18577c8436a10651c07e5a2e9f5fdb1ea
          ports:
            - containerPort: 3100          
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
          env:
            - name: PELIAS_CONFIG
              value: "/etc/config/pelias.json"
      volumes:
        - name: config-volume
          configMap:
            name: pelias-configmap 
            items:
              - key: pelias.json
                path: pelias.json

