apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pelias-api-hpa
  namespace: geocoder
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pelias-api
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 65
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 65