apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - virtualService.yaml
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: pelias-api
        namespace: geocoder
      spec:
        template:
          spec:
            containers:
              - name: pelias-api
                resources:
                  requests:
                    cpu: 200m
                    memory: 400Mi
              - name: istio-proxy
                image: auto
                resources:
                  requests:
                    cpu: 50m
                    memory: 112Mi
                securityContext:
                  allowPrivilegeEscalation: false
    target:
      kind: Deployment
      name: pelias-api
      namespace: geocoder
