apiVersion: batch/v1
kind: Job
metadata:
  name: polylines-importer
  namespace: default
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      initContainers:
        - name: polylines-download
          image: ghcr.io/valhalla/valhalla@sha256:828581dd89478a618d1ccc68a2d9a761484ba3e8e9ac67b65bd74023dbcf48af
          workingDir: /home
          command: 
            - sh
            - -c
            - |
              rm -rf /data/polylines 
              mkdir -p /data/polylines
              valhalla_build_tiles -c valhalla.json /data/openstreetmap/canada-latest.osm.pbf
              valhalla_export_edges --config valhalla.json > /data/polylines/extract.0sv
          volumeMounts:
            - name: data-volume
              mountPath: /data
            - name: tiles-volume
              mountPath: /home/valhalla_tiles
            - name: config-volume
              mountPath: /home/valhalla.json
              subPath: valhalla.json
          env:
            - name: PELIAS_CONFIG
              value: "/etc/config/pelias.json"
          resources:
            limits:
              memory: 10Gi
              ephemeral-storage: 10Gi
              cpu: 1
            requests:
              memory: 10Gi
              ephemeral-storage: 10Gi
              cpu: 1
      containers:
        - name: polylines-import
          image: pelias/polylines:v3.0.0
          command: ["./bin/start"]
          volumeMounts:
            - name: data-volume
              mountPath: /data
            - name: config-volume
              mountPath: /code/pelias.json
              subPath: pelias.json
          resources:
            limits:
              cpu: 1
              memory: 4Gi
      restartPolicy: Never
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
      volumes:
        - name: config-volume
          configMap:
            name: pelias-configmap
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-volume
        - name: tiles-volume
          emptyDir: {}
