apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -f docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: csv-importer
  name: csv-importer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: csv-importer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v -f docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network: "true"
        io.kompose.service: csv-importer
    spec:
      containers:
        - image: pelias/csv-importer:master
          name: pelias-csv-importer
          resources: {}
          securityContext:
            runAsUser: 1000
          volumeMounts:
            - mountPath: /code/pelias.json
              name: csv-importer-claim0
            - mountPath: /data
              name: csv-importer-claim1
            - mountPath: /data/blacklist
              name: csv-importer-claim2
      restartPolicy: Always
      volumes:
        - name: csv-importer-claim0
          persistentVolumeClaim:
            claimName: csv-importer-claim0
        - name: csv-importer-claim1
          persistentVolumeClaim:
            claimName: csv-importer-claim1
        - name: csv-importer-claim2
          persistentVolumeClaim:
            claimName: csv-importer-claim2
status: {}
