apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -f docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: interpolation
  name: interpolation
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: interpolation
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v -f docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/: "true"
        io.kompose.service: interpolation
    spec:
      containers:
        - env:
            - name: PORT
              value: "4300"
          image: pelias/interpolation:master
          name: pelias-interpolation
          ports:
            - containerPort: 4300
          resources: {}
          securityContext:
            runAsUser: 1000
          volumeMounts:
            - mountPath: /code/pelias.json
              name: interpolation-claim0
            - mountPath: /data
              name: interpolation-claim1
      restartPolicy: Always
      volumes:
        - name: interpolation-claim0
          persistentVolumeClaim:
            claimName: interpolation-claim0
        - name: interpolation-claim1
          persistentVolumeClaim:
            claimName: interpolation-claim1
status: {}
