apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -f docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: libpostal
  name: libpostal-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: libpostal
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v -f docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network: "true"
        io.kompose.service: libpostal
    spec:
      containers:
        - image: pelias/libpostal-service
          name: pelias-libpostal
          ports:
            - containerPort: 4400
          resources: {}
          securityContext:
            runAsUser: 1000
      restartPolicy: Always
status: {}
