apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -v -f docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: libpostal
  name: libpostal
spec:
  ports:
    - name: "4400"
      port: 4400
      targetPort: 4400
  selector:
    io.kompose.service: libpostal
status:
  loadBalancer: {}
