apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -f docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: openaddresses
  name: openaddresses-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: openaddresses
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v -f docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network: "true"
        io.kompose.service: openaddresses
    spec:
      containers:
        - image: pelias/openaddresses:master
          name: pelias-openaddresses
          resources: {}
          securityContext:
            runAsUser: 1000
          volumeMounts:
            - mountPath: /code/pelias.json
              name: openaddresses-claim0
            - mountPath: /data
              name: openaddresses-claim1
      restartPolicy: Always
      volumes:
        - name: openaddresses-claim0
          persistentVolumeClaim:
            claimName: openaddresses-claim0
        - name: openaddresses-claim1
          persistentVolumeClaim:
            claimName: openaddresses-claim1
status: {}
