apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -v -f docker-compose.yml
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: transit
  name: transit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: transit
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -v -f docker-compose.yml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network: "true"
        io.kompose.service: transit
    spec:
      containers:
        - image: pelias/transit:master
          name: pelias-transit
          resources: {}
          securityContext:
            runAsUser: 1000
          volumeMounts:
            - mountPath: /code/pelias.json
              name: transit-claim0
            - mountPath: /data
              name: transit-claim1
      restartPolicy: Always
      volumes:
        - name: transit-claim0
          persistentVolumeClaim:
            claimName: transit-claim0
        - name: transit-claim1
          persistentVolumeClaim:
            claimName: transit-claim1
status: {}
