apiVersion: apps/v1
kind: Deployment
metadata:
  name: interpolation
  namespace: geocoder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interpolation
  template:
    metadata:
      labels:
        app: interpolation
    spec:
      containers:
        - name: pelias-interpolation-service
          image: pelias/interpolation:v2.23.0
          ports:
            - containerPort: 4300          
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
            - name: data-volume
              mountPath: /data
          env:
            - name: PELIAS_CONFIG
              value: "/etc/config/pelias.json"
            - name: PORT
              value: "4300"
          resources:
            requests:
              cpu: 500m
              memory: 1Gi 
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
        runAsNonRoot: true               
      volumes:
        - name: config-volume
          configMap:
            name: pelias-configmap 
            items:
              - key: pelias.json
                path: pelias.json
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-volume

