apiVersion: v1
kind: Service
metadata:
    name: interpolation
    namespace: geocoder
spec:
    selector:
        app: interpolation
    ports:
        - protocol: TCP
          port: 4300
          targetPort: 4300
