apiVersion: batch/v1
kind: Job
metadata:
  name: openaddresses-importer
  namespace: geocoder  
spec:
  backoffLimit: 0 
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"  
    spec:
      initContainers:
        - name: openaddresses-download
          image: pelias/openaddresses:v4.0.0
          command: ["./bin/download"]
          volumeMounts:
          - name: data-volume
            mountPath: /data
          - name: config-volume
            mountPath: /code/pelias.json
            subPath: pelias.json
      containers:
        - name: openaddresses-import
          image: pelias/openaddresses:v4.0.0
          command: ["./bin/start"]
          resources:
            limits:
              cpu: 2
              memory: 16Gi
          volumeMounts:
            - name: data-volume
              mountPath: /data
            - name: config-volume
              mountPath: /code/pelias.json
              subPath: pelias.json
      restartPolicy: Never
      securityContext:
        fsGroup: 1000
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-volume
        - name: config-volume
          configMap:
            name: pelias-configmap
