apiVersion: batch/v1
kind: Job
metadata:
  name: data-downloader
spec:
  backoffLimit: 0 
  template:
    spec:
      containers:
        - name: whosonfirst-download
          image: pelias/whosonfirst:master
          command: ["./bin/download"]
          volumeMounts:
            - name: data-volume
              mountPath: /data
            - name: config-volume
              mountPath: /code/pelias.json
              subPath: pelias.json
            - name: config-volume
              mountPath: /data/blacklist/osm.txt
              subPath: osm.txt
        - name: openaddresses-download
          image: pelias/openaddresses:master
          command: ["./bin/download"]
          volumeMounts:
          - name: data-volume
            mountPath: /data
          - name: config-volume
            mountPath: /code/pelias.json
            subPath: pelias.json
          - name: config-volume
            mountPath: /data/blacklist/osm.txt
            subPath: osm.txt
        - name: openstreetmap-download
          image: pelias/openstreetmap:master
          command: ["./bin/download"]
          volumeMounts:
          - name: data-volume
            mountPath: /data
          - name: config-volume
            mountPath: /code/pelias.json
            subPath: pelias.json
          - name: config-volume
            mountPath: /data/blacklist/osm.txt
            subPath: osm.txt
      restartPolicy: Never
      securityContext:
        fsGroup: 1000
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-volume
        - name: config-volume
          configMap:
            name: pelias-configmap
