apiVersion: batch/v1
kind: Job
metadata:
  name: polylines-download
spec:
  template:
    metadata:
      name: polylines-download
    spec:
      initContainers:
          - name: setup
            image: busybox
            command: ["/bin/sh","-c"]
            args: ["rm -rf /data/polylines; mkdir -p /data/polylines && chown 1000:1000 /data/polylines"]
            volumeMounts:
              - name: data-volume
                mountPath: /data
      containers:
          - name: polylines-download-container
            image: ghcr.io/valhalla/valhalla:latest
            command: ["/bin/bash","-c"]
            args: ["valhalla_build_config --mjolnir-tile-dir valhalla_tiles --mjolnir-tile-extract valhalla_tiles.tar --mjolnir-timezone valhalla_tiles/timezones.sqlite --mjolnir-admin valhalla_tiles/admins.sqlite > valhalla.json; valhalla_build_tiles -c valhalla.json /data/openstreetmap/canada-latest.osm.pbf; valhalla_export_edges --config valhalla.json > /data/polylines/my_extract.0sv"]
            volumeMounts:
              - name: config-volume
                mountPath: /etc/config
              - name: data-volume
                mountPath: /data
            env:
              - name: PELIAS_CONFIG
                value: "/etc/config/pelias.json"
            resources:
                limits:
                    memory: 10Gi
                    ephemeral-storage: 10Gi
                requests:
                    memory: 10Gi
                    ephemeral-storage: 10Gi                
      restartPolicy: Never
      volumes:
        - name: config-volume
          configMap:
            name: pelias-json-configmap
            items:
              - key: pelias.json
                path: pelias.json
        - name: data-volume
          persistentVolumeClaim:
            claimName: data-volume

