# Removing the Auth Policy from the setup
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: elasticsearch
  namespace: geocoder
spec:
  selector:
    matchLabels:
      common.k8s.elastic.co/type: elasticsearch
  rules:
  - from:
    - source:
        namespaces: ["geocoder", "elastic-system"]
  - to:
    - operation:
        methods: ["GET"]