apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: geocoder
spec:
  version: 7.16.1
  count: 1
  elasticsearchRef:
    name: quickstart
  config:
    server.host: "0.0.0.0"