steps:
  # Step 1: Combine commands to generate a commit tag with SHA and timestamp, then build the Docker image.
  - name: 'gcr.io/cloud-builders/git'
    id: 'get-commit-sha'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Generate the shortened commit SHA and timestamp
        COMMIT_SHA=$(git rev-parse HEAD | cut -c 1-7)
        DATE=$(date +%Y%m%d%H%M%S)
        COMMIT_TAG="main-$COMMIT_SHA-$DATE"
        echo $COMMIT_TAG > /workspace/commit_tag.txt

        # Build the Docker image using the generated tag
        docker build --pull --cache-from "northamerica-northeast1-docker.pkg.dev/phx-01hnn9wb0eg/pelias-geocoder/ui:$COMMIT_TAG" \
                     -t "northamerica-northeast1-docker.pkg.dev/phx-01hnn9wb0eg/pelias-geocoder/ui:$COMMIT_TAG" .
    dir: 'ui'

  # Step 2: Test the newly built Docker image to ensure it exists.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'test-docker-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        COMMIT_TAG=$(cat /workspace/commit_tag.txt)
        if docker image inspect "northamerica-northeast1-docker.pkg.dev/phx-01hnn9wb0eg/pelias-geocoder/ui:$COMMIT_TAG" > /dev/null; then
          echo "Docker image exists."
          exit 0
        else
          echo "Docker image does not exist."
          exit 1
        fi
    dir: 'ui'

  # Step 3: Push the Docker image to a container registry.
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-docker-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        COMMIT_TAG=$(cat /workspace/commit_tag.txt)
        docker push "northamerica-northeast1-docker.pkg.dev/phx-01hnn9wb0eg/pelias-geocoder/ui:$COMMIT_TAG"
