steps:
  # Captures the current commit SHA and exports it as an environment variable
  - name: 'gcr.io/cloud-builders/git'
    id: 'get-commit-sha'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        COMMIT_SHA=$(git rev-parse HEAD)
        echo "export COMMIT_SHA=$COMMIT_SHA" > /workspace/commit_sha.sh
        chmod +x /workspace/commit_sha.sh

  # Source the commit SHA and build the Docker image using it
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-docker-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/commit_sha.sh
        docker build -t "northamerica-northeast1-docker.pkg.dev/phx-01hnn9wb0eg/pelias-geocoder/ui:$COMMIT_SHA" .
    dir: 'ui'
    waitFor: ['get-commit-sha']

  # Source the commit SHA again and test if the Docker image was built successfully
  - name: 'gcr.io/cloud-builders/docker'
    id: 'test-docker-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/commit_sha.sh
        if docker image inspect "northamerica-northeast1-docker.pkg.dev/phx-01hnn9wb0eg/pelias-geocoder/ui:$COMMIT_SHA" > /dev/null; then
          echo "Docker image exists."
          exit 0
        else
          echo "Docker image does not exist."
          exit 1
        fi
    dir: 'ui'
    waitFor: ['build-docker-image']

  # Source the commit SHA once more and push the Docker image if on the main branch
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-docker-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        source /workspace/commit_sha.sh
        if [ "$_IS_MAIN_BRANCH" = "true" ]; then
          docker push "northamerica-northeast1-docker.pkg.dev/phx-01hnn9wb0eg/pelias-geocoder/ui:$COMMIT_SHA"
        else
          echo "Not pushing image as this is not the main branch."
        fi
    waitFor: ['test-docker-image']

images:
  - 'northamerica-northeast1-docker.pkg.dev/phx-01hnn9wb0eg/pelias-geocoder/ui:$COMMIT_SHA'

substitutions:
  _IS_MAIN_BRANCH: 'false'
  COMMIT_SHA: 'latest'  # Default, will be overridden by actual commit SHA in the build process.

options:
  substitutionOption: 'ALLOW_LOOSE'