steps:
  # Captures the current commit SHA and exports it for subsequent steps
  - name: 'gcr.io/cloud-builders/git'
    id: 'get-commit-sha'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        COMMIT_SHA=$(git rev-parse HEAD)
        echo $COMMIT_SHA > commit_sha.txt

  # Builds the Docker image using the commit SHA from a file
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-docker-image'
    args: ['build', '-t', 'northamerica-northeast1-docker.pkg.dev/phx-01hnn9wb0eg/pelias-geocoder/ui:$(cat commit_sha.txt)', '.']
    dir: 'ui'
    waitFor: ['get-commit-sha']

  # Tests if the Docker image was built successfully
  - name: 'gcr.io/cloud-builders/docker'
    id: 'test-docker-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if docker image inspect northamerica-northeast1-docker.pkg.dev/phx-01hnn9wb0eg/pelias-geocoder/ui:$(cat ../commit_sha.txt) > /dev/null; then
          echo "Docker image exists."
          exit 0
        else
          echo "Docker image does not exist."
          exit 1
        fi
    dir: 'ui'
    waitFor: ['build-docker-image']

  # Pushes the Docker image to the registry if the current branch is the main branch
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-docker-image'
    args: ['push', 'northamerica-northeast1-docker.pkg.dev/phx-01hnn9wb0eg/pelias-geocoder/ui:$(cat commit_sha.txt)']
    waitFor: ['test-docker-image']
    condition: '$_IS_MAIN_BRANCH == "true"'

images:
  - 'northamerica-northeast1-docker.pkg.dev/phx-01hnn9wb0eg/pelias-geocoder/ui:$(cat commit_sha.txt)'

substitutions:
  _IS_MAIN_BRANCH: 'false'

options:
  substitutionOption: 'ALLOW_LOOSE'
