steps:
  # Captures the current commit SHA and writes it to a file
  - name: 'gcr.io/cloud-builders/git'
    id: 'get-commit-sha'
    entrypoint: 'bash'
    args:
      - '-c'
      - 'echo "$(git rev-parse HEAD)" > /workspace/commit_sha.txt'

  # Builds the Docker image using the commit SHA from the file
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-docker-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        COMMIT_SHA=$(cat /workspace/commit_sha.txt)
        docker build -t "northamerica-northeast1-docker.pkg.dev/phx-01hnn9wb0eg/pelias-geocoder/ui:$COMMIT_SHA" .
    dir: 'ui'
    waitFor: ['get-commit-sha']

  # Tests if the Docker image was built successfully
  - name: 'gcr.io/cloud-builders/docker'
    id: 'test-docker-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        COMMIT_SHA=$(cat /workspace/commit_sha.txt)
        if docker image inspect "northamerica-northeast1-docker.pkg.dev/phx-01hnn9wb0eg/pelias-geocoder/ui:$COMMIT_SHA" > /dev/null; then
          echo "Docker image exists."
          exit 0
        else
          echo "Docker image does not exist."
          exit 1
        fi
    dir: 'ui'
    waitFor: ['build-docker-image']

  # Pushes the Docker image to the registry if on the main branch
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-docker-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        COMMIT_SHA=$(cat /workspace/commit_sha.txt)
        if [ "$_IS_MAIN_BRANCH" = "true" ]; then
          docker push "northamerica-northeast1-docker.pkg.dev/phx-01hnn9wb0eg/pelias-geocoder/ui:$COMMIT_SHA"
        else
          echo "Not pushing image as this is not the main branch."
        fi
    waitFor: ['test-docker-image']

substitutions:
  _IS_MAIN_BRANCH: 'false'

options:
  substitutionOption: 'ALLOW_LOOSE'

