steps:
- name: 'gcr.io/cloud-builders/git'
  id: 'setup-environment'
  entrypoint: 'bash'
  args:
    - './setup_env.sh'
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-docker-image'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      source .env.cloud_build
      docker build --tag "gcr.io/$PROJECT_ID/my-app:$IMAGE_TAG" .
- name: 'gcr.io/cloud-builders/docker'
  id: 'push-docker-image'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      source .env.cloud_build
      docker push "gcr.io/$PROJECT_ID/my-app:$IMAGE_TAG"