steps:
  - name: 'gcr.io/cloud-builders/git'
    id: 'get-commit-sha'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Capture the current commit SHA
        COMMIT_SHA=$(git rev-parse HEAD | cut -c 1-7)
        echo "COMMIT_SHA=$COMMIT_SHA" > /workspace/env_vars.sh

  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-docker-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Source environment variables and perform Docker build using the TIMESTAMP substitution
        source /workspace/env_vars.sh
        docker build --pull --cache-from "northamerica-northeast1-docker.pkg.dev/phx-01hnn9wb0eg/pelias-geocoder/ui:main-$COMMIT_SHA-${_TIMESTAMP}" \
                     -t "northamerica-northeast1-docker.pkg.dev/phx-01hnn9wb0eg/pelias-geocoder/ui:main-$COMMIT_SHA-${_TIMESTAMP}" .
    dir: 'ui'
    waitFor: ['get-commit-sha']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'test-docker-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Verify the existence of the Docker image using the TIMESTAMP substitution
        source /workspace/env_vars.sh
        if docker image inspect "northamerica-northeast1-docker.pkg.dev/phx-01hnn9wb0eg/pelias-geocoder/ui:main-$COMMIT_SHA-${_TIMESTAMP}" > /dev/null; then
          echo "Docker image exists."
          exit 0
        else
          echo "Docker image does not exist."
          exit 1
        fi
    dir: 'ui'
    waitFor: ['build-docker-image']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-docker-image'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Push the Docker image to the registry using the TIMESTAMP substitution
        source /workspace/env_vars.sh
        docker push "northamerica-northeast1-docker.pkg.dev/phx-01hnn9wb0eg/pelias-geocoder/ui:main-$COMMIT_SHA-${_TIMESTAMP}"
    waitFor: ['test-docker-image']