apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- gw-certificate.yaml
- mesh-gateway.yaml
- ingress.yaml
- namespace.yaml
- prometheus.yaml
- kiali.yaml
- mesh-wide-mTLS.yaml
patches:
# Patch the Istio ingress service so that our IP is used.
- patch: |-
    - op: add
      path: /spec/loadBalancerIP
      value: 34.118.185.223
  target:
    kind: Service
    name: istio-ingressgateway
    namespace: istio-ingress
    version: v1